### ISSUE TITLE
blocks inside curly braces do not auto indent

### ISSUE THREAD

**Issue by djh1202** [emacs-ess/ess-stata-mode#3]
in a conditional or for loop inside braces { } , do not automatically indent as they used to

**Comment by BrendanHalpin** [comment]
As far as I know, support for indentation was removed quite some time ago

**Comment by BrendanHalpin** [comment]
Support was withdrawn because indentation was driven by the R indentation framework, and it was felt inappropriate to support this (it is clearly imperfect). 

You can re-activate R-style indentation by putting the following after (require 'ess) in your startup:

```emacs-lisp
(require 'ess-r-mode)
(add-to-list 'STA-customize-alist '(indent-line-function . #'ess-r-indent-line))
```

**Comment by djh1202** [comment]
Thanks! I had to change (require 'ess-r-mode) to (require 'ess-stata-mode) in my init file, but after that it worked.
